// <auto-generated />
using System;
using MetricsManagerAPI.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MetricsManagerAPI.Migrations
{
    [DbContext(typeof(ManagerDbContext))]
    [Migration("20211018230502_InitAgentsAndCpuMetrics")]
    partial class InitAgentsAndCpuMetrics
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0-rc.2.21480.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MetricsManagerAPI.Models.AgentInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("MetricsManagerAPI.Models.CpuProcessorTimeTotalMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<long>("RetrieveTime")
                        .HasColumnType("bigint");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("CpuProcessorTimeTotalMetrics");
                });

            modelBuilder.Entity("MetricsManagerAPI.Models.CpuProcessorTimeTotalMetric", b =>
                {
                    b.HasOne("MetricsManagerAPI.Models.AgentInfo", "Agent")
                        .WithMany("CpuProcessorTimeTotalMetrics")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("MetricsManagerAPI.Models.AgentInfo", b =>
                {
                    b.Navigation("CpuProcessorTimeTotalMetrics");
                });
#pragma warning restore 612, 618
        }
    }
}
